# Class 01: Numpy 基礎操作

首先一定要嚴正聲明  
.py --> python檔案  
.ipynb --> 一個可以跑python的 "筆記" 檔  
**寫code一律給我用 .py 不要用 .ipynb**  
  
( by 資管113級 陳啟誠 學長)

### 載入第三方模組 Numpy

In [2]:
# 常見的用法: 把numpy縮寫成np
import numpy as np

當然，你想把np改成其他也行  
自己記得就好......

In [13]:
# 確認numpy版本至少要 2.x.x
print(np.version.version)

2.1.3


### 建立array

In [149]:
nparray = np.array([0, 1, 1, 2, 3, 5])
print(nparray)

[0 1 1 2 3 5]


#### 為什麼要使用array?  
 - 使用資料的效率較高
 - 不用loop就可以對整個array進行運算(迴圈很吃資源的......)
 - 減少記憶體的使用

In [150]:
# 確認array內的資料型態
print(nparray.dtype)

int64


### 方便的偷懶用函式

#### 1. zeros(): array裡面的值全部都是0

In [151]:
# np.zeros(data shape, data type)
print(np.zeros(2, dtype = "float32"))
print(np.zeros((2, 3)))

[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


#### 2. ones(): array裡面的值全部都是1

In [152]:
# np.ones(data shape, data type)
print(np.ones((3, 2), dtype = "int64"))

[[1 1]
 [1 1]
 [1 1]]


#### 3. full(): array裡面全部都是特定值

In [153]:
# np.full(data shape, value, data type)
print(np.full([4, 4], 8, dtype = "int32"))

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


#### 4. arange(): 建立一個等差array

In [ ]:
# np.arange(起始值, 終止值(不會印出), 步數)
print(np.arange(2, 20, 2))

[ 2  4  6  8 10 12 14 16 18]
[ 3  6  9 12 15 18]


#### 5. linespace(): 指定範圍內需要多少個資料

In [16]:
# np.linespace(起始值, 終止值, 資料數量) (包括兩端點)
print(np.linspace(13.5, 50.4, 100))

[13.5        13.87272727 14.24545455 14.61818182 14.99090909 15.36363636
 15.73636364 16.10909091 16.48181818 16.85454545 17.22727273 17.6
 17.97272727 18.34545455 18.71818182 19.09090909 19.46363636 19.83636364
 20.20909091 20.58181818 20.95454545 21.32727273 21.7        22.07272727
 22.44545455 22.81818182 23.19090909 23.56363636 23.93636364 24.30909091
 24.68181818 25.05454545 25.42727273 25.8        26.17272727 26.54545455
 26.91818182 27.29090909 27.66363636 28.03636364 28.40909091 28.78181818
 29.15454545 29.52727273 29.9        30.27272727 30.64545455 31.01818182
 31.39090909 31.76363636 32.13636364 32.50909091 32.88181818 33.25454545
 33.62727273 34.         34.37272727 34.74545455 35.11818182 35.49090909
 35.86363636 36.23636364 36.60909091 36.98181818 37.35454545 37.72727273
 38.1        38.47272727 38.84545455 39.21818182 39.59090909 39.96363636
 40.33636364 40.70909091 41.08181818 41.45454545 41.82727273 42.2
 42.57272727 42.94545455 43.31818182 43.69090909 44.06363636 44.4

#### 6. random.randint(): 指定範圍內的隨機整數

In [156]:
print(np.random.randint(1, 100, [3, 5]))
print(np.random.randint(77, 999, [5, 6]))

[[46 74 70 35 71]
 [54 44 97 29 44]
 [10 69 42 48  6]]
[[712 947 905 845 804 126]
 [153 107 140 285 974 707]
 [162 107 605 212 982 595]
 [488 754 962 897 468 197]
 [643 100 571 984 895 676]]


### Array 的資料讀取  
基本上跟 Python 內建的 list 操作很像

In [157]:
x1 = np.arange(0, 12)
print(x1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [158]:
print(x1[4])

4


In [159]:
print(x1[-3])

9


In [160]:
x1 = x1.reshape(4, 3)
print(x1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [161]:
print("ndim:", x1.ndim)
print("shape:", x1.shape)
print("size:", x1.size)
print("dtype:", x1.dtype)
print("itemsize:", x1.itemsize, "bytes")
print("nbytes:", x1.nbytes, "bytes")

ndim: 2
shape: (4, 3)
size: 12
dtype: int64
itemsize: 8 bytes
nbytes: 96 bytes


In [162]:
print(x1[3, -2])

10


In [163]:
x1[2, 1] = 100
print(x1)

[[  0   1   2]
 [  3   4   5]
 [  6 100   8]
 [  9  10  11]]


### Array Slicing
透過特殊的 Query 方式得到 Subarrays

In [164]:
x2 = np.arange(0, 12)
print(x2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [165]:
#切片皆不含右端點
print(x2[:5])
print(x2[3:8])
print(x2[::-2])
print(x2[x2 > 5])
print(x2[x2 % 4 == 0])

[0 1 2 3 4]
[3 4 5 6 7]
[11  9  7  5  3  1]
[ 6  7  8  9 10 11]
[0 4 8]


In [166]:
print(x1)
print("\n")
# 取0, 1, 2列，行從後面數回來
print(x1[:3, ::-1])

[[  0   1   2]
 [  3   4   5]
 [  6 100   8]
 [  9  10  11]]


[[  2   1   0]
 [  5   4   3]
 [  8 100   6]]


In [167]:
x1_sub = x1[:2, :2]
print(x1_sub)

[[0 1]
 [3 4]]


In [168]:
# 重新賦值會改到原值(call by address)，若不想改到，則要用copy
x1_sub[0, 0] = 99
print(x1)

[[ 99   1   2]
 [  3   4   5]
 [  6 100   8]
 [  9  10  11]]


##### Note: 這種Slicing只是「一種觀察原始array的方法」  
要創造一個獨立的array需要使用函式 copy()

In [169]:
x1_sub = x1.copy()[:2, :2]
x1_sub[0, 0] = 0
print(x1)
print(x1_sub)

[[ 99   1   2]
 [  3   4   5]
 [  6 100   8]
 [  9  10  11]]
[[0 1]
 [3 4]]


In [170]:
x1 = x1.reshape(x1.size)
print(x1)

[ 99   1   2   3   4   5   6 100   8   9  10  11]


#### 小練習1

1. 建立一個 1 ~ 20 的一維陣列

In [171]:
Q1 = np.arange(1, 21)

2. 印出所有「偶數index」的值

In [172]:
print(Q1[0::2])

[ 1  3  5  7  9 11 13 15 17 19]


3. 印出所有「偶數」

In [173]:
print(Q1[Q1 % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20]


4. 取出第 5 ~ 15 的值，且每隔2個取一次

In [174]:
print(Q1[5:16:2])

[ 6  8 10 12 14 16]


5. 將陣列反轉

In [175]:
Q1 = Q1[::-1]
print(Q1)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


### Array的合併與分割

In [17]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [18]:
print(np.concatenate([x, y]))
print(np.concatenate([x.reshape(3, 1), y.reshape(3, 1)], axis = 1))

[1 2 3 3 2 1]
[[1 3]
 [2 2]
 [3 1]]


In [178]:
# vertical stack
x3 = np.vstack([x, y])
print(x3)

[[1 2 3]
 [3 2 1]]


In [179]:
# horizontal stack
temp = np.array([99, 99]).reshape(2, 1)
x3 = np.hstack([x3, temp])
print(x3)

[[ 1  2  3 99]
 [ 3  2  1 99]]


In [180]:
print(x1)
# np.split(array name, 2nd array's start element, 3rd array's start element...)
s1, s2, s3 = np.split(x1, [3, 8])
print(s1)
print(s2)
print(s3)

[ 99   1   2   3   4   5   6 100   8   9  10  11]
[99  1  2]
[  3   4   5   6 100]
[ 8  9 10 11]


In [181]:
upper, lower = np.vsplit(x3, [1])
print(upper)
print(lower)
left, right = np.hsplit(x3, [2])
print(left)
print(right)

[[ 1  2  3 99]]
[[ 3  2  1 99]]
[[1 2]
 [3 2]]
[[ 3 99]
 [ 1 99]]


In [182]:
print(x3)
print(x3.T)
print(x3.transpose())

[[ 1  2  3 99]
 [ 3  2  1 99]]
[[ 1  3]
 [ 2  2]
 [ 3  1]
 [99 99]]
[[ 1  3]
 [ 2  2]
 [ 3  1]
 [99 99]]


### Numpy array的運算

In [183]:
x = np.arange(4)

In [184]:
print("x = ", x)
print("x + 5 =", x + 5)
print("x -  5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print( "x // 2 =", x // 2)

x =  [0 1 2 3]
x + 5 = [5 6 7 8]
x -  5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


還有下面的函式可以使用:  
- np.sum(): 求出array內值的總和
- np.min(): 找出最小值
- np.max(): 找出最大值  
  
以及參數 axis:
- axis = 0: 以每個row進行計算
- axis = 1: 以每個column進行計算

#### 小練習2

In [185]:
y = np.arange(0, 24)

1. 將 y 重塑為 4 x 6 的陣列

In [186]:
y = y.reshape(4, 6)
print(y.reshape(4, 6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


2. 將 y 重塑為 2 x 4 x 3 的陣列

In [187]:
# 2個2維陣列，4列3行
y = y.reshape(2, 4, 3)
print(y.reshape(2, 4, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


3. 透過運算，讓前一題陣列中的每一個值都變成原本的10倍

In [188]:
y *= 10
print(y)

[[[  0  10  20]
  [ 30  40  50]
  [ 60  70  80]
  [ 90 100 110]]

 [[120 130 140]
  [150 160 170]
  [180 190 200]
  [210 220 230]]]


### Broadcasting: 當 array 大小不同時

In [189]:
# 當兩個array的列與行不完全相同時-->broadcasting
# broadcasting: 若兩個array的行or列任一者相同時即適用，缺失元素的array會複製自己，最後進行運算
a = np.array([1, 2, 3])
m = np.ones((3, 3))
print(a)
print(m)

[1 2 3]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [190]:
print(a + m)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [191]:
n = np.arange(3).reshape(3, 1)
print(n)

[[0]
 [1]
 [2]]


In [192]:
print(a)
print(n)
print(a + n)

[1 2 3]
[[0]
 [1]
 [2]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


#### 小練習3

1. 建立一個 3 x 4 的隨機整數陣列 x (範圍 1 ~ 10)

In [193]:
x = np.array(np.random.randint(1, 11, [3, 4]))
print(x)

[[5 5 1 3]
 [5 6 9 8]
 [6 7 3 5]]


2. 建立一個值為 [10, 20, 30, 40] 的陣列 y

In [194]:
y = np.arange(10, 50, 10)
print(y)

[10 20 30 40]


3. x, y 相加

In [195]:
print(x + y)

[[15 25 31 43]
 [15 26 39 48]
 [16 27 33 45]]


4. 創建一個(3, 1)的隨機整數陣列 z，並與 x 相乘 (範圍 1 ~ 10)

In [196]:
z = np.array(np.random.randint(1, 11, [3, 1]))
print(z)
print(x * z)

[[10]
 [ 8]
 [10]]
[[50 50 10 30]
 [40 48 72 64]
 [60 70 30 50]]


5. 計算 z 每個 row 的總和

In [197]:
print(np.sum(z, axis = 1))

[10  8 10]


6. 取 z 每個 column 的最小值

In [198]:
print(np.min(z, axis = 1))

[10  8 10]


#### Advance 1: Slicing
現在有一個 5 x 7 的陣列 x ，初始設定裡面的值皆為0  
現在希望你透過上面學到的 Slicing，將x的前4個row與前6個column改成像這樣:  
$$
\begin{bmatrix}
0 & 1 & 2 & 2 & 2 & 2 \\
0 & 1 & 2 & 2 & 2 & 2 \\
3 & 4 & 3 & 4 & 5 & 5 \\
3 & 4 & 3 & 4 & 5 & 5 \\
\end{bmatrix}
$$
  
但是，這裡有幾個限制條件:  
- 只能動到前4個row與前6個column，其他地方在過程中不能被更動到
- 不能直接用「選定特定位置並賦值」的方式
- 在6個步驟中完成(一個動作一行程式)

In [199]:
x = np.zeros([5, 7])
print("Before:")
print(x)
##########################################################################
# 你的code寫在這裡
x[:2, 1] = 1
x[:2, 2:6] = 2
x[2:4, :4:2] = 3
x[2:4, 1:5:2] = 4
x[2:4, 4:6] = 5
##########################################################################
print("\nAfter:")
print(x)
expected = [
    [0, 1, 2, 2, 2, 2, 0],
    [0, 1, 2, 2, 2, 2, 0],
    [3, 4, 3, 4, 5, 5, 0],
    [3, 4, 3, 4, 5, 5, 0],
    [0, 0, 0, 0, 0, 0, 0],
]
print('\nCorrect: ', x.tolist() == expected)

Before:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

After:
[[0. 1. 2. 2. 2. 2. 0.]
 [0. 1. 2. 2. 2. 2. 0.]
 [3. 4. 3. 4. 5. 5. 0.]
 [3. 4. 3. 4. 5. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Correct:  True


In [200]:
x = np.zeros([5, 7])
print("Before:")
print(x)
##########################################################################
# 你的code寫在這裡
x += [[0, 1, 2, 2, 2, 2, 0],
     [0, 1, 2, 2, 2, 2, 0],
     [3, 4, 3, 4, 5, 5, 0],
     [3, 4, 3, 4, 5, 5, 0],
     [0, 0, 0, 0, 0, 0, 0]]
##########################################################################
print("\nAfter:")
print(x)
expected = [
    [0, 1, 2, 2, 2, 2, 0],
    [0, 1, 2, 2, 2, 2, 0],
    [3, 4, 3, 4, 5, 5, 0],
    [3, 4, 3, 4, 5, 5, 0],
    [0, 0, 0, 0, 0, 0, 0],
]
print('\nCorrect: ', x.tolist() == expected)

Before:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

After:
[[0. 1. 2. 2. 2. 2. 0.]
 [0. 1. 2. 2. 2. 2. 0.]
 [3. 4. 3. 4. 5. 5. 0.]
 [3. 4. 3. 4. 5. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Correct:  True


### Advance 2: 分割與合併
現在有一個 0 ~ 23 的一維 array，請試著將 array 變成下面的樣子:  
$$
\begin{bmatrix}
0 & 1 & 2 & 3 & 12 & 13 & 14 & 15\\
4 & 5 & 6 & 7 & 16 & 17 & 18 & 19 \\
8 & 9 & 10 & 11 & 20 & 21 & 22 & 23 \\
\end{bmatrix}
$$  
  
  
提示: 先把原本的 y 變成兩個2維的陣列吧

In [201]:
y = np.arange(24)
print("Before:")
print(y)
##########################################################################
# 你的code寫在這裡
y = y.reshape(6, 4)
upper, lower = np.vsplit(y, [3])
y = np.concatenate([upper, lower], axis = 1)
##########################################################################
print("\nAfter:")
print(y)

expected = [
    [0, 1,  2,  3, 12, 13, 14, 15],
    [4, 5,  6,  7, 16, 17, 18, 19],
    [8, 9, 10, 11, 20, 21, 22, 23]]
print('\nCorrect:', y.tolist() == expected)

Before:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

After:
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]

Correct: True
