若本文的資訊有誤，請聯絡我

# 前置作業


## 引入Numpy
習慣上我們會這麼引入(以np作為numpy的縮寫)

In [ ]:
import numpy as np

# Numpy Intro

## Numpy簡介
Numpy 是 python 中重要且基礎的 Package，Numpy 支援許多多維度陣列與矩陣運算的數學函式庫，在科學與工程領域中有相當廣泛的用途。

其核心以C語言開發，在運算上相當迅速。

## Numpy的陣列(Array)簡介

**左邊有灰色一條標起來的段落，參考即可(不一定要看)**

> Python 的 List 是一個很棒的容器，List 中可以同時包含許多不同類型的物件，並且 List 在元素不多的情況下，操作速度相當的快。

> 但在某些情況下，我們基本上只會用到一種類型的物件(如整數)，此時想在 CPU 上處理大量「相同型別」的資料時，就可以利用 Numpy 提高速度並減少記憶體消耗。

> 在 Numpy 中我們使用 Array 來代替 Python 的 List，Numpy 中的 Array 類似於 C/C++ 中Array，但比起 C/C++ 中的 Array，Numpy 為其實作了許多功能，使其便於使用。

對於沒有學過 C/C++ 或除了Python以外程式語言的人來說，Numpy 的 Array 類似於 Python 的 List，現階段只需知道它在細節與底層的實作上與 Python 的 List 不太一樣。

---

**大多數** NumPy Array 有一些限制：

*   Array的所有元素必須具有相同的資料型別。
*   一旦創建，Array的**總**大小就不能改變。
*   形狀必須是“矩形”

當滿足這些條件時，NumPy 就可以利用這些特性使陣列比起限制較少的資料結構來的更快、更有效率、更方便使用。

# 建立一個Numpy陣列

對於Numpy的陣列，我們一樣可以用print()將他印到螢幕上，進行觀察

接著我們將來介紹一些基礎的建立陣列方法

### array
透過現有的物件建立陣列(可以用Python的List來建立)

In [ ]:
import numpy as np
# 註釋: 中括號中的是可以省略的部分

# array(object[, dtype, copy, order, subok, ...])
data = np.array([1,2,3])    #一維陣列 3
print("Array:\n",data)
data = np.array([       #二維陣列 2x3
    [1,2,3],
    [4,5,6]
])
print("Array:\n",data)
data = np.array([       #三維陣列 2x3x4
    [
        [1,2,3,4],
        [5,6,7,8],
        [1,1,1,1]
    ],
    [
        [2,4,6,8],
        [4,3,2,1],
        [0,0,0,0]
    ]
])
print("Array:\n",data)


Array:
 [1 2 3]
Array:
 [[1 2 3]
 [4 5 6]]
Array:
 [[[1 2 3 4]
  [5 6 7 8]
  [1 1 1 1]]

 [[2 4 6 8]
  [4 3 2 1]
  [0 0 0 0]]]


### arrange
類似於 Python 中的 range()，只是現在回傳的是 numpy 的陣列

In [ ]:
import numpy as np
# 註釋: 中括號中的是可以省略的部分

# arange([start,] stop[, step,][, dtype, ...])
data = np.arange(10)
print(data)
print(np.arange(3,10))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[3 5 7 9]


### linspace
有點像在一個線段上取好幾個點的座標，來做為陣列的資料
(在一個線段上採樣好幾個點)

In [ ]:

import numpy as np
# 註釋: 中括號中的是可以省略的部分

# linspace(start, stop[, num=50][, endpoint=True][, retstep=False][, dtype=None][, axis=0, ....])
print(np.linspace(2.0, 3.0, num=5))           # [2. 2.25 2.5 2.75 3.]  #相當於在2.0和3.0的線段中找五個點(等距)
print(np.linspace(2.0, 3.0, num=5, endpoint=False))   # [2.  2.2 2.4 2.6 2.8] #在2.0到3.0中插五個點(3.0不算)
print(np.linspace(2.0, 3.0, num=5, retstep=True))   # (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) #那個0.25是每個元素之間的距離

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


## 更多: 透過給定形狀或數值建立陣列

### empty
回傳給定形狀和類型的新陣列(未初始化)。

In [ ]:
import numpy as np
# 註釋: 中括號中的是可以省略的部分

# empty(shape[, dtype, order, device, like])
#   回傳給定形狀和類型的新陣列(未初始化)。
#   shape: 這個矩陣的構成是長怎麼樣的，通常傳入的是tuple ex. (2,3)
data = np.empty((2,3))
print("Empty:\n",data)
print("Empty:\n",np.empty((2,)))
print("Empty:\n",np.empty((2,3,4)))

Empty:
 [[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
Empty:
 [-2.00000000e+000  6.95312411e-310]
Empty:
 [[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
  [2.5e-323 3.0e-323 3.5e-323 4.0e-323]
  [4.9e-324 4.9e-324 4.9e-324 4.9e-324]]

 [[9.9e-324 2.0e-323 3.0e-323 4.0e-323]
  [2.0e-323 1.5e-323 9.9e-324 4.9e-324]
  [0.0e+000 0.0e+000 0.0e+000 0.0e+000]]]


### ones
回傳給定形狀和類型的新陣列，並用1填滿。

In [ ]:
import numpy as np
# 註釋: 中括號中的是可以省略的部分

# ones(shape[, dtype, order, device, like])
#   回傳給定形狀和類型的新陣列，並用1填滿。
#   shape: 這個矩陣的構成是長怎麼樣的，通常傳入的是tuple ex. (2,3)
data = np.ones((2,3))
print("ones:\n",data)
print("ones:\n",np.ones(2,))
print("ones:\n",np.ones((2,3,4)))

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
ones:
 [1. 1.]
ones:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### zeros
回傳給定形狀和類型的新陣列，並用0填滿。

In [ ]:
import numpy as np
# 註釋: 中括號中的是可以省略的部分

# zeros(shape[, dtype, order, like])
#   回傳給定形狀和類型的新陣列，並用0填滿。
#   shape: 這個矩陣的構成是長怎麼樣的，通常傳入的是tuple ex. (2,3)
data = np.zeros((2,3))
print("zeros:\n",data)
print("zeros:\n",np.zeros(2,))
print("zeros:\n",np.zeros((2,3,4)))

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
zeros:
 [0. 0.]
zeros:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### full
回傳給定形狀和類型的新陣列，並用指定的數值填滿。

In [ ]:
import numpy as np
# 註釋: 中括號中的是可以省略的部分

# full(shape, fill_value[, dtype, order, ...])
#   回傳給定形狀和類型的新陣列，並用指定的數值填滿。
#   shape: 這個矩陣的構成是長怎麼樣的，通常傳入的是tuple ex. (2,3)
#   fill_value: 以什麼數字填滿
data = np.full((2,3),4)
print("full:\n",data)
print("full:\n",np.full((2,),5))
print("full:\n",np.full((2,3,4),1))

full:
 [[4 4 4]
 [4 4 4]]
full:
 [5 5]
full:
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


### identity
回傳一個單位矩陣

In [ ]:
import numpy as np
# 註釋: 中括號中的是可以省略的部分

# identity(n[, dtype, like])
#   回傳一個單位矩陣
#   n: 幾成幾的單位矩陣
data = np.identity(2)
print("Identity:\n",data)
print("Identity:\n",np.identity(3))
print("Identity:\n",np.identity(4))

Identity:
 [[1. 0.]
 [0. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


除了這些方法外，其實還有許多建立陣列的方法，有興趣的可以自行查閱。

# 陣列的基礎屬性

ndim 　 : 陣列的維度

shape　: 陣列的形狀

size　　: 陣列的元素總數



In [ ]:
data = np.array([1,2,3])    #一維陣列 3
print("維度:",data.ndim)
print("形狀:",data.shape)
print("元素總數:",data.size)
print(len(data.shape)==data.ndim) #觀察一下
temp = 1
for i in data.shape:temp*=i
print(temp == data.size)    #觀察一下

維度: 1
形狀: (3,)
元素總數: 3
True
True


In [ ]:
data = np.array([       #二維陣列 2x3
    [1,2,3],
    [4,5,6]
])
print("維度:",data.ndim)
print("形狀:",data.shape)
print("元素總數:",data.size)
print(len(data.shape)==data.ndim) #觀察一下
temp = 1
for i in data.shape:temp*=i
print(temp == data.size)    #觀察一下

維度: 2
形狀: (2, 3)
元素總數: 6
True
True


In [ ]:
data = np.array([       #三維陣列 2x3x4
    [
        [1,2,3,4],
        [5,6,7,8],
        [1,1,1,1]
    ],
    [
        [2,4,6,8],
        [4,3,2,1],
        [0,0,0,0]
    ]
])
print("維度:",data.ndim)
print("形狀:",data.shape)
print("元素總數:",data.size)
print(len(data.shape)==data.ndim) #觀察一下
temp = 1
for i in data.shape:temp*=i
print(temp == data.size)    #觀察一下
print()

維度: 3
形狀: (2, 3, 4)
元素總數: 24
True
True



# 陣列的一些操作

## 形狀操作、扁平化

In [ ]:
import numpy as np
#
#   扁平化
#
data = np.array([
    [1,2,3],
    [4,5,6]
])
print(data.ravel())
print(data.flatten())

# 到這裡你可能會想:這兩個有啥差別
# 最大的差異即是: flatten是建立副本(修改不會改到原本的資料)、ravel則是參考(修改會改到原本的資料)
print("Flatten")
d1 = data.flatten()
d1[0] = 2
print(d1)
print(data)

print("Ravel")
d2 = data.ravel()
d2[0] = 2
print(d2)
print(data)   # 看到了嗎? 他會改變原本的data!!!
# ravel的操作通常會比flatten來的快，可以視自己的需求來決定要使用哪一個

[1 2 3 4 5 6]
[1 2 3 4 5 6]
Flatten
[2 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
Ravel
[2 2 3 4 5 6]
[[2 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
#
#   column_stack 把很多個1D-array 當作column疊起來產生新的2D陣列
#
a = np.array((1,2,3))
b = np.array((4,5,6))
c = np.array((5,6,7))
print(np.column_stack((a,b,c)))
# [[1 4 5]
#  [2 5 6]
#  [3 6 7]]
err = np.array((1,2,3,4))
# print(np.column_stack((a,b,c,err))) #error size要一樣!!!

[[1 4 5]
 [2 5 6]
 [3 6 7]]


In [ ]:
import numpy as np
#
# Reshape
#
data = np.array([ #4x3  12
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
print(data.shape,data.size) #(4,3) 12
print(data.reshape(2,6),"  2x6\n")
print(data.reshape(2,2,3),"  2x2x3\n")
print(data.reshape(6,2),"  6x2\n")
# print(data.reshape(3,5))  #ERROR, 注意: 使用Reshape時，括號裡面的數字乘起來要和data.size相同

print(np.arange(1,13).reshape(4,3))

(4, 3) 12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]   2x6

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]   2x2x3

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]   6x2

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 索引、切片

In [ ]:
import numpy as np
#
#   索引 Indexing
#
# 概念上和python的索引相同
# 從0開始遞增
data = np.array([4,6,2,1,9])
print(data)
print(data[0])      #4
print(data[2])      #2
print(data[-1])     #9
print(data[data<5])   #[4 2 1] 所有小於 5 的值

print()
data = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(data[0,2])    #3
print(data[1,1])    #6
print(data[1,0])    #5
print(data[0])     #[1 2 3 4]  #索引索引數少於維度的多維陣列，則會得到一個亞維陣列
print(data[0][1])   #2  #效率較data[0,1]低

[4 6 2 1 9]
4
2
9
[4 2 1]

3
6
5
[1 2 3 4]
2


In [ ]:
import numpy as np
#
# 切片 Slicing
#
# 用法語python相似
data = np.array([3,4,1,5,6,1,8,2])
print(data[0:2])    #[3 4]
print(data[1:4])    #[4 1 5]
print(data[2:])     #[1 5 6 1 8 2]
print(data[:3])     #[3 4 1]
print(data[:])      #[3 4 1 5 6 1 8 2]
print(data[2:7:2])  #[1 6 8]

print()
data = np.array([
    [3,1,2,1],
    [1,2,5,2],
    [5,2,2,3],
    [3,-5,1,4]
])
print(data[2:4,1:3])    #[[ 2  2] [-5  1]]
print(data[0:2,1])      #[1 2]

print(data[2:4])        # [[ 5  2  2  3] [ 3 -5  1  4]]
print(data[2:4][1:3])   #[[ 3 -5  1  4]]
print("\n...")
#使用...代表我全都要!
data = np.array([
    [
        [3,1,2],
        [1,0,5]
    ],
    [
        [5,4,3],
        [1,3,-3]
    ]
])
print(data[1,...])
print(data[...,0:2])

[3 4]
[4 1 5]
[1 5 6 1 8 2]
[3 4 1]
[3 4 1 5 6 1 8 2]
[1 6 8]

[[ 2  2]
 [-5  1]]
[1 2]
[[ 5  2  2  3]
 [ 3 -5  1  4]]
[[ 3 -5  1  4]]

...
[[ 5  4  3]
 [ 1  3 -3]]
[[[3 1]
  [1 0]]

 [[5 4]
  [1 3]]]


## 轉置

In [ ]:
data = np.arange(1,10).reshape(3,3)
print("原資料:\n",data)
transpose = data.T
print("轉置:\n",transpose)

原資料:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
轉置:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


# 陣列運算

## 陣列間四則運算

In [ ]:
d1 = np.array([
    [1,2],
    [3,4]
])
d2 = np.array([
    [5,6],
    [7,8]
])
print(d1+d2)
print(d1-d2)
print(d1/d2)

print("-------")
#乘法比較需要注意
print("*\n",d1*d2)  #是元素相乘而已，不是數學定義的那種普通矩陣乘法
print("multiply\n",np.multiply(d1,d2))

print("-------")
#數學上面的普通矩陣乘法
print("@\n", d1@d2)
print("matmul\n",np.matmul(d1,d2))
print("dot\n",np.dot(d1,d2))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
-------
*
 [[ 5 12]
 [21 32]]
multiply
 [[ 5 12]
 [21 32]]
-------
@
 [[19 22]
 [43 50]]
matmul
 [[19 22]
 [43 50]]
dot
 [[19 22]
 [43 50]]


## 陣列與數字間四則運算

In [ ]:
data = np.arange(8).reshape(2,4)
number = 2
print(data)
print("+\n",data+number)
print("-\n",data-number)
print("*\n",data*number)
print("/\n",data/number)

[[0 1 2 3]
 [4 5 6 7]]
+
 [[2 3 4 5]
 [6 7 8 9]]
-
 [[-2 -1  0  1]
 [ 2  3  4  5]]
*
 [[ 0  2  4  6]
 [ 8 10 12 14]]
/
 [[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]]


## 最大、最小、平均、加總、相乘、標準差

In [ ]:
data = np.arange(1,10)
print(data.max())
print(data.min())
print(data.mean())  #平均
print(data.sum())   #所有元素加總
print(data.prod())  #所有元素相乘
print(data.std())   #標準差

9
1
5.0
45
362880
2.581988897471611


## 反矩陣、四捨五入

In [ ]:
arr = np.array([
    [1,2,3],
    [2,9,3],
    [1,0,4]
])
print(np.linalg.inv(arr))
print("相乘應為單位矩陣，但好像不是那麼一回事???")
newarr = np.matmul(arr, np.linalg.inv(arr))
print(newarr)
# 仔細觀察 3.55271368e-15 -1.77635684e-15 ，你會發現是10^-15這種很小的值 => 我猜測是電腦浮點數乘法的計算誤差
# 如果你去手算np.matmul(arr, np.linalg.inv(arr)) 應該會發現是單位矩陣沒錯
print("四捨五入 Round")
print(np.around(newarr))    #四捨五入到整數位
print(np.around(newarr,14))  #四捨五入到小數點第14位
print(np.around(newarr,15))  #四捨五入到小數點第15位

[[-36.   8.  21.]
 [  5.  -1.  -3.]
 [  9.  -2.  -5.]]
相乘應為單位矩陣，但好像不是那麼一回事???
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.55271368e-15  1.00000000e+00 -1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
四捨五入 Round
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
[[ 1.e+00  0.e+00  0.e+00]
 [ 4.e-15  1.e+00 -2.e-15]
 [ 0.e+00  0.e+00  1.e+00]]
